add hw_6
interpparietes/homework_5-sem pull request #3
Opened 2023-10-30 16:21 UTC by interpparietes

6 домашка! посмотрите, пожалуйста!

2023-11-01 11:32 UTC, fortvivlan requested changes
Пока засчитываю 2 задачи из 4 - переделайте, пожалуйста, 1 и 2 задачи из домашки. Можно мне снова кинуть ревью, там кнопочка будет "обновить".

2023-11-01 11:32 UTC, fortvivlan commented on Kremneva_hw06.ipynb
> +        "for word in range(len(words)):\n",
А если в списке будут слова, а не цифры? и в случайном порядке? Эту задачку надо переделать как-то по-другому.

2023-11-01 11:32 UTC, fortvivlan commented on Kremneva_hw06.ipynb
> +        "# не могу понять, как сделать сортировку по всем буквам сразу - for-ы все ломают\n",
а почему бы вашей функции не возвращать список номеров юникода, например? Списки между собой тоже отлично сортируются. Попробуйте так сделать, тогда лямбда окажется вообще не нужна.

2023-11-01 11:32 UTC, fortvivlan commented on Kremneva_hw06.ipynb
> +        "yo_alphabet = 'ёбвгдежзийклмнопрстуфхцчщшъыьююя'\n",
одно но - в юникоде маленькая ё в конце после всех букв, а большая Ё в начале перед всеми буквами... не уверена, что такое решение будет работать совсем для всего (для верхнего регистра точно не будет)

2023-11-01 11:32 UTC, fortvivlan commented on Kremneva_hw06.ipynb
> +        "# дошло, что с генератором в два раза короче\n",
а с ключом сортировки вообще в одну строчку.)

2023-11-01 11:32 UTC, fortvivlan commented on Kremneva_hw06.ipynb
> +        "print(numbers)"
здесь большой беды не будет, но обычно удалять элементы из списка лучше в цикле while.

2023-11-02 13:20 UTC, interpparietes commented
исправила 1 и 2 задачи)

2023-11-03 11:06 UTC, fortvivlan approved these changes
теперь ок)

2023-11-03 13:26 UTC, interpparietes commented
ура! спасибо)

2023-11-03 13:26 UTC, merged